[package]
name = "tauvlo_trustlines"
description = "ERC20 token with trustlines"
version = "0.1.0"
edition = "2023_11"
cairo-version = "2.6.3"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
[dependencies]
starknet = ">=2.0.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.13.0" }

[[target.starknet-contract]]
sierra = true
casm = true

